-- MySQL Script generated by MySQL Workbench
-- Mon May  7 15:22:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kong
-- -----------------------------------------------------
-- 孔

-- -----------------------------------------------------
-- Schema kong
--
-- 孔
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kong` DEFAULT CHARACTER SET utf8 ;
USE `kong` ;

-- -----------------------------------------------------
-- Table `kong`.`albumtype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`albumtype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `album_type_id` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `album_type_name` CHAR(4) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `album_type_id_UNIQUE` (`album_type_id` ASC),
  UNIQUE INDEX `album_type_name_UNIQUE` (`album_type_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kong`.`media_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`media_source` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `media_url_small` VARCHAR(255) NULL,
  `media_url_middle` VARCHAR(255) NULL,
  `media_url_origin` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '图片表',
  `media_datas` BLOB NULL,
  `media_description` VARCHAR(255) NULL,
  `createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `author` VARCHAR(60) NULL,
  `org` VARCHAR(255) NULL,
  `title` VARCHAR(30) NULL,
  `media_type` VARCHAR(6) NULL COMMENT '媒体类型。音乐/音乐/视屏/',
  `media_catagory` VARCHAR(6) NULL COMMENT '媒体目录。 风景。。人物….',
  `media_origin_size` VARCHAR(16) NULL COMMENT '图片元素尺寸\n1080*720\nFormat : {width}*{height}\n',
  `user_id` INT NULL DEFAULT 0,
  `album_id` INT NULL DEFAULT 0,
  `media_catagory_id` INT NULL DEFAULT 0 COMMENT '视频目录辑的id ',
  PRIMARY KEY (`media_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '图片';


-- -----------------------------------------------------
-- Table `kong`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `album_name` VARCHAR(45) NOT NULL DEFAULT '',
  `album_photo` INT NULL DEFAULT 0 COMMENT '相册封面照\n图片的id',
  `album_description` VARCHAR(255) NULL DEFAULT '',
  `album_creator` VARCHAR(16) NULL DEFAULT '',
  `createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `album_type` INT NULL,
  `albumtype_id` INT NOT NULL,
  `media_source_media_id` INT NOT NULL,
  PRIMARY KEY (`id`, `albumtype_id`, `media_source_media_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_albums_albumtype_idx` (`albumtype_id` ASC),
  INDEX `fk_albums_media_source1_idx` (`media_source_media_id` ASC),
  CONSTRAINT `fk_albums_albumtype`
    FOREIGN KEY (`albumtype_id`)
    REFERENCES `kong`.`albumtype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_media_source1`
    FOREIGN KEY (`media_source_media_id`)
    REFERENCES `kong`.`media_source` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '相册';


-- -----------------------------------------------------
-- Table `kong`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `userid` INT NOT NULL AUTO_INCREMENT,
  `albums_id` INT NOT NULL,
  `albums_albumtype_id` INT NOT NULL,
  PRIMARY KEY (`userid`, `albums_id`, `albums_albumtype_id`),
  INDEX `fk_user_albums1_idx` (`albums_id` ASC, `albums_albumtype_id` ASC),
  CONSTRAINT `fk_user_albums1`
    FOREIGN KEY (`albums_id` , `albums_albumtype_id`)
    REFERENCES `kong`.`albums` (`id` , `albumtype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `kong`.`qxw_login_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`qxw_login_records` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL COMMENT '用户id',
  `company_id` INT NULL COMMENT '企业id',
  `login_time` TIMESTAMP NULL COMMENT '登录时间',
  `login_role_id` INT NULL COMMENT '用户角色',
  `login_ip` INT(10) NULL COMMENT '登录ip地址',
  `login_areakey` CHAR(8) NULL COMMENT '登录的区域key',
  `login_method` CHAR(8) NULL COMMENT 'wx，qq,ali,passwd,code',
  PRIMARY KEY (`record_id`))
ENGINE = InnoDB;

CREATE USER 'xkong' IDENTIFIED BY 'xkong6666';

GRANT ALL ON `kong`.* TO 'xkong';
GRANT SELECT ON TABLE `kong`.* TO 'xkong';
GRANT SELECT, INSERT, TRIGGER ON TABLE `kong`.* TO 'xkong';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `kong`.* TO 'xkong';
GRANT EXECUTE ON ROUTINE `kong`.* TO 'xkong';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `kong`.`albumtype`
-- -----------------------------------------------------
START TRANSACTION;
USE `kong`;
INSERT INTO `kong`.`albumtype` (`id`, `album_type_id`, `album_type_name`) VALUES (1, 0, '默认');
INSERT INTO `kong`.`albumtype` (`id`, `album_type_id`, `album_type_name`) VALUES (2, 1, '风景');
INSERT INTO `kong`.`albumtype` (`id`, `album_type_id`, `album_type_name`) VALUES (3, 2, '人物');
INSERT INTO `kong`.`albumtype` (`id`, `album_type_id`, `album_type_name`) VALUES (4, 3, '动物');
INSERT INTO `kong`.`albumtype` (`id`, `album_type_id`, `album_type_name`) VALUES (5, 4, '生活');
INSERT INTO `kong`.`albumtype` (`id`, `album_type_id`, `album_type_name`) VALUES (6, 5, '音乐');

COMMIT;

